version: '3'

services:
  postgres_db:
    container_name: postgres
    image: postgres:15
    env_file: ".env"
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data
      - ./etc/postgres/database.ddl:/etc/app/database.ddl
      - ./etc/postgres/init_ddl.sh:/docker-entrypoint-initdb.d/init-schema-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB", ]
      interval: 5s
      timeout: 5s
      retries: 10

  etl:
    container_name: etl
    env_file: ".env"
    build: etl
    restart: on-failure
    volumes:
      - ./etl/data.xml:/opt/app/data.xml # Data to be processed
    depends_on:
      postgres_db:
        condition: service_healthy


